openapi: 3.0.0
info:
  description: "Microservicio para la gestión de usuarios, multicuentas y métodos de pago en Cineverse"
  title: Cineverse Usuarios API
  version: 1.1.0
servers:
- url: http://localhost:8080/api
paths:
  /usuarios:
    delete:
      description: Elimina la cuenta del usuario principal y todos sus perfiles asociados.
      operationId: eliminar_usuario
      responses:
        "200":
          description: Usuario eliminado correctamente
        "404":
          description: Usuario no encontrado
      summary: Eliminar usuario principal
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      description: Permite registrar un nuevo usuario principal en la plataforma Cineverse.
      operationId: registrar_usuario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioRegistro'
        required: true
      responses:
        "201":
          description: Usuario registrado exitosamente
        "400":
          description: Datos inválidos
      summary: Registro de nuevo usuario
      x-openapi-router-controller: openapi_server.controllers.default_controller
    put:
      description: Modifica los datos personales del usuario principal autenticado.
      operationId: modificar_usuario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      responses:
        "200":
          description: Usuario actualizado correctamente
        "404":
          description: Usuario no encontrado
      summary: Modificación de datos del usuario principal
      x-openapi-router-controller: openapi_server.controllers.default_controller

  /usuarios/datos:
    get:
      description: Obtiene la información del usuario autenticado.
      operationId: usuarios_id_get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
          description: Datos del usuario obtenidos exitosamente
        "404":
          description: Usuario no encontrado
      summary: Obtener datos del usuario autenticado
      x-openapi-router-controller: openapi_server.controllers.default_controller

  /usuarios/favoritos:
    post:
      summary: Agregar película a favoritos
      description: Permite al usuario agregar una película a sus favoritos.
      operationId: añadir_favorito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                peliculaId:
                  type: integer
                  description: ID de la película a agregar
              required:
                - peliculaId
      responses:
        "201":
          description: Película agregada a favoritos correctamente
        "400":
          description: El ID de la película es requerido
        "500":
          description: Error al agregar la película a favoritos
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      summary: Obtener películas favoritas
      description: Permite al usuario obtener la lista de sus películas favoritas.
      operationId: obtener_favoritos
      responses:
        "200":
          description: Lista de películas favoritas obtenida correctamente
        "500":
          description: Error al obtener las películas favoritas
      x-openapi-router-controller: openapi_server.controllers.default_controller

  /usuarios/login:
    post:
      description: Autentica a un usuario usando su correo electrónico y contraseña.
      operationId: login_usuario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        "200":
          description: Autenticación exitosa
        "401":
          description: Credenciales incorrectas
      summary: Autenticación de usuario
      x-openapi-router-controller: openapi_server.controllers.default_controller

  /usuarios/perfiles:
    post:
      description: Permite al usuario principal crear múltiples perfiles bajo la misma cuenta para diferentes personas.
      operationId: crear_perfil
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerfilUsuario'
        required: true
      responses:
        "201":
          description: Perfil creado exitosamente
        "400":
          description: Datos inválidos
      summary: Crear un nuevo perfil de usuario (multicuentas)
      x-openapi-router-controller: openapi_server.controllers.default_controller
    put:
      description: Cambia entre perfiles de usuario disponibles bajo la cuenta principal basado en el nombre del perfil.
      operationId: cambiar_perfil
      parameters:
      - name: nombrePerfil
        in: query
        description: El nombre del perfil al cual cambiar
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Cambio de perfil exitoso
        "404":
          description: Perfil no encontrado
      summary: Cambiar de perfil
      x-openapi-router-controller: openapi_server.controllers.default_controller

  /usuarios/metodos-pago:
    post:
      description: Permite añadir un nuevo método de pago a la cuenta del usuario.
      operationId: agregar_metodo_pago
      requestBody:
        description: Datos del nuevo método de pago
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetodoPago'
      responses:
        "201":
          description: Método de pago añadido correctamente
        "400":
          description: Datos inválidos
      summary: Añadir método de pago
      x-openapi-router-controller: openapi_server.controllers.default_controller

components:
  schemas:
    UsuarioRegistro:
      example:
        nombreUsuario: "Juan"
        apellido: "Pérez"
        correoElectronico: "juan.perez@example.com"
        contrasena: "miContrasenaSegura"
        fechaNacimiento: "1990-01-01"
      properties:
        nombreUsuario:
          type: string
        apellido:
          type: string
        correoElectronico:
          type: string
        contrasena:
          type: string
        fechaNacimiento:
          type: string
          format: date
      type: object

    Usuario:
      example:
        nombreUsuario: "Juan"
        apellido: "Pérez"
        correoElectronico: "juan.perez@example.com"
        contrasena: "miContrasenaSegura"
      properties:
        nombreUsuario:
          type: string
        apellido:
          type: string
        correoElectronico:
          type: string
        contrasena:
          type: string
      type: object

    favoritos:
      example:
        peliculaId: 1
      properties:
        peliculaId:
          type: integer
          description: ID de la película a agregar
      type: object

    PerfilUsuario:
      example:
        id: 1
        nombrePerfil: "Perfil1"
        avatarPerfil: "avatar1.png"
      properties:
        id:
          type: integer
        nombrePerfil:
          type: string
        avatarPerfil:
          type: string
      type: object

    Login:
      example:
        correoElectronico: "juan.perez@example.com"
        contrasena: "miContrasenaSegura"
      properties:
        correoElectronico:
          type: string
        contrasena:
          type: string
      type: object

    MetodoPago:
      example:
        tipoTarjeta: "Visa"
        numeroTarjeta: "4111111111111111"
        fechaExpiracion: "2025-12-31"
        cvv: "123"
      properties:
        tipoTarjeta:
          type: string
          enum:
            - Visa
            - MasterCard
            - American Express
            - Discover
        numeroTarjeta:
          type: string
        fechaExpiracion:
          type: string
          format: date
        cvv:
          type: string
      type: object
